import type { Company, FormTemplate, Vessel } from "./types"

export const DEFAULT_COMPANIES: Company[] = [
  { id: "c-seanutri", name: "SEANUTRI", createdAt: new Date().toISOString() },
  { id: "c-asso-maritima", name: "ASSO MARÍTIMA", createdAt: new Date().toISOString() },
  { id: "c-asgaard-bourbon", name: "ASGAARD BOURBON", createdAt: new Date().toISOString() },
]

// ==========================================
// Default Vessels (demo data)
// ==========================================

export const DEFAULT_VESSELS: Vessel[] = [
  { id: "v1", name: "MV Atlantic Explorer", companyId: "c-seanutri" },
  { id: "v2", name: "MV Pacific Star", companyId: "c-seanutri" },
  { id: "v3", name: "MV Southern Cross", companyId: "c-seanutri" },
  { id: "v4", name: "MV Northern Light", companyId: "c-asso-maritima" },
  { id: "v5", name: "MV Coral Reef", companyId: "c-asso-maritima" },
]

// ==========================================
// Form Templates
// ==========================================

export const DEFAULT_TEMPLATES: FormTemplate[] = [
  {
    id: "tpl-refeicoes",
    name: "Controle de Refeicoes",
    shortName: "Refeicoes",
    type: "refeicoes",
    version: "1.0",
    description:
      "Registro diario de refeicoes servidas a bordo, incluindo tipo de refeicao, quantidade e responsavel.",
    sections: [
      {
        id: "sec-refeicao",
        title: "Dados da Refeicao",
        fields: [
          {
            id: "tipo_refeicao",
            label: "Tipo de Refeicao",
            type: "select",
            required: true,
            options: [
              "Cafe da Manha",
              "Almoco",
              "Jantar",
              "Ceia",
              "Lanche",
            ],
            width: "half",
          },
          {
            id: "horario",
            label: "Horario",
            type: "time",
            required: true,
            width: "half",
          },
          {
            id: "quantidade_servida",
            label: "Qtd. Servida",
            type: "number",
            required: true,
            placeholder: "Numero de porcoes",
            min: 0,
            max: 500,
            width: "half",
          },
          {
            id: "temperatura_alimento",
            label: "Temp. Alimento (C)",
            type: "temperature",
            required: true,
            min: -30,
            max: 150,
            unit: "C",
            width: "half",
          },
          {
            id: "descricao_cardapio",
            label: "Descricao do Cardapio",
            type: "textarea",
            required: false,
            placeholder: "Descreva o cardapio servido",
            width: "full",
          },
          {
            id: "responsavel",
            label: "Responsavel",
            type: "text",
            required: true,
            placeholder: "Nome do responsavel",
            width: "half",
          },
          {
            id: "observacoes",
            label: "Observacoes",
            type: "textarea",
            required: false,
            placeholder: "Observacoes adicionais",
            width: "full",
          },
        ],
      },
    ],
    supportsMultipleRows: true,
    createdAt: new Date().toISOString(),
  companyIds: ["c-seanutri","c-asso-maritima","c-asgaard-bourbon"],
  },
  {
    id: "tpl-descongelamento",
    name: "Controle de Descongelamento",
    shortName: "Descongelamento",
    type: "descongelamento",
    version: "1.0",
    description:
      "Controle do processo de descongelamento de alimentos, com registro de temperaturas e horarios.",
    sections: [
      {
        id: "sec-descongelamento",
        title: "Dados do Descongelamento",
        fields: [
          {
            id: "produto",
            label: "Produto",
            type: "text",
            required: true,
            placeholder: "Nome do produto",
            width: "half",
          },
          {
            id: "quantidade_kg",
            label: "Quantidade (kg)",
            type: "number",
            required: true,
            placeholder: "Peso em kg",
            min: 0,
            max: 1000,
            unit: "kg",
            width: "half",
          },
          {
            id: "hora_inicio",
            label: "Hora Inicio",
            type: "time",
            required: true,
            width: "half",
          },
          {
            id: "hora_fim",
            label: "Hora Fim",
            type: "time",
            required: false,
            width: "half",
          },
          {
            id: "temp_inicial",
            label: "Temp. Inicial (C)",
            type: "temperature",
            required: true,
            min: -30,
            max: 150,
            unit: "C",
            width: "half",
          },
          {
            id: "temp_final",
            label: "Temp. Final (C)",
            type: "temperature",
            required: false,
            min: -30,
            max: 150,
            unit: "C",
            width: "half",
          },
          {
            id: "metodo",
            label: "Metodo",
            type: "select",
            required: true,
            options: [
              "Refrigerador",
              "Agua corrente",
              "Microondas",
              "Ambiente",
            ],
            width: "half",
          },
          {
            id: "responsavel",
            label: "Responsavel",
            type: "text",
            required: true,
            placeholder: "Nome do responsavel",
            width: "half",
          },
          {
            id: "observacoes",
            label: "Observacoes",
            type: "textarea",
            required: false,
            placeholder: "Observacoes adicionais",
            width: "full",
          },
        ],
      },
    ],
    supportsMultipleRows: true,
    createdAt: new Date().toISOString(),
  companyIds: ["c-seanutri","c-asso-maritima","c-asgaard-bourbon"],
  },
  {
    id: "tpl-equipamentos",
    name: "Controle de Temperatura de Equipamentos",
    shortName: "Equipamentos",
    type: "equipamentos",
    version: "1.0",
    description:
      "Registro de temperaturas de equipamentos de refrigeracao e congelamento (camaras, freezers, geladeiras).",
    sections: [
      {
        id: "sec-equipamento",
        title: "Dados do Equipamento",
        fields: [
          {
            id: "equipamento",
            label: "Equipamento",
            type: "select",
            required: true,
            options: [
              "Camara Fria 1",
              "Camara Fria 2",
              "Freezer 1",
              "Freezer 2",
              "Geladeira Cozinha",
              "Geladeira Refeitorio",
            ],
            width: "half",
          },
          {
            id: "hora_verificacao",
            label: "Hora Verificacao",
            type: "time",
            required: true,
            width: "half",
          },
          {
            id: "temperatura",
            label: "Temperatura (C)",
            type: "temperature",
            required: true,
            min: -30,
            max: 150,
            unit: "C",
            width: "half",
          },
          {
            id: "status_equipamento",
            label: "Status",
            type: "select",
            required: true,
            options: ["Normal", "Alerta", "Critico", "Desligado"],
            width: "half",
          },
          {
            id: "responsavel",
            label: "Responsavel",
            type: "text",
            required: true,
            placeholder: "Nome do responsavel",
            width: "half",
          },
          {
            id: "acao_corretiva",
            label: "Acao Corretiva",
            type: "textarea",
            required: false,
            placeholder: "Descreva a acao corretiva (se necessario)",
            width: "full",
          },
        ],
      },
    ],
    supportsMultipleRows: true,
    createdAt: new Date().toISOString(),
  companyIds: ["c-seanutri","c-asso-maritima","c-asgaard-bourbon"],
  },
  {
    id: "tpl-higienizacao",
    name: "Controle de Higienizacao",
    shortName: "Higienizacao",
    type: "higienizacao",
    version: "1.0",
    description:
      "Registro de procedimentos de higienizacao de areas e equipamentos da cozinha.",
    sections: [
      {
        id: "sec-higienizacao",
        title: "Dados da Higienizacao",
        fields: [
          {
            id: "area_equipamento",
            label: "Area/Equipamento",
            type: "text",
            required: true,
            placeholder: "Area ou equipamento higienizado",
            width: "half",
          },
          {
            id: "horario",
            label: "Horario",
            type: "time",
            required: true,
            width: "half",
          },
          {
            id: "produto_utilizado",
            label: "Produto Utilizado",
            type: "text",
            required: true,
            placeholder: "Nome do produto de limpeza",
            width: "half",
          },
          {
            id: "concentracao",
            label: "Concentracao",
            type: "text",
            required: false,
            placeholder: "Ex: 1:100",
            width: "half",
          },
          {
            id: "responsavel",
            label: "Responsavel",
            type: "text",
            required: true,
            placeholder: "Nome do responsavel",
            width: "half",
          },
          {
            id: "conforme",
            label: "Conforme",
            type: "select",
            required: true,
            options: ["Sim", "Nao"],
            width: "half",
          },
          {
            id: "observacoes",
            label: "Observacoes",
            type: "textarea",
            required: false,
            placeholder: "Observacoes adicionais",
            width: "full",
          },
        ],
      },
    ],
    supportsMultipleRows: true,
    createdAt: new Date().toISOString(),
  companyIds: ["c-seanutri","c-asso-maritima","c-asgaard-bourbon"],
  },
]
